services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      DB_URL: jdbc:postgresql://db:5432/barber-shop-api
      DB_USER: barber-shop-api
      DB_PASSWORD: barber-shop-api
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/barber-shop-api:z
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: barber-shop-api
      POSTGRES_PASSWORD: barber-shop-api
      POSTGRES_DB: barber-shop-api
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "5432:5432"
volumes:
  db: